### ISSUE TITLE
afterSave hook: data is single object (not array) and update queries don't include RETURNING columns

### ISSUE THREAD

**Issue by cpirich** [romeerez/orchid-orm#670]
## Summary

After upgrading from orchid-orm 1.58 to 1.64, `afterSave` hooks have two breaking behavioral changes:

1. The hook callback receives a **single record object** instead of an array of records
2. For **update** queries, the hook receives the **row count** (a number) instead of the selected column data

## Reproduction

Table definition:

```ts
export class IntegrationsTable extends BaseTable {
  readonly table = "integrations";
  columns = this.setColumns((t) => ({
    id: t.identity().primaryKey(),
    credentials: t.json().nullable(),
    // ...
  }));

  init() {
    this.afterSave(["credentials"], (data) => {
      // In 1.58: data was an array of { credentials: ... } objects
      // In 1.64: data is a single object (the full record on create, or the number 1 on update)
      data.map(({ credentials }) => {
        if (credentials) {
          validateCredentials(credentials);
        }
      });
    });
  }
}
```

Test case:

```ts
// This triggers afterSave on CREATE - hook receives single full record object (not array)
const integration = await db.integrations.create({ credentials: null });

// This triggers afterSave on UPDATE - hook receives the number 1 (row count), not column data
await db.integrations.find(integration.id).update({
  credentials: someValue,
});
```

## Issue 1: Single object instead of array

On both create and update, the hook receives a single record object rather than an array. Calling `data.map(...)` fails with `TypeError: data.map is not a function`.

The TypeScript types suggest `data` should be an array, so this appears to be a type/runtime mismatch.

## Issue 2: Update queries ignore afterSaveSelect columns

This is the more significant issue. We traced it through the internals:

- `afterSave(["credentials"], cb)` stores the column selection in `q.q.afterSaveSelect` (via the `after()` helper at ~line 4329)
- The hook callbacks are correctly gathered for update queries at ~line 4969: `afterSaveHooks = q.afterSave`
- However, `makeReturningSql` (line 10248) only checks `q.q.afterUpdateSelect`:
  ```js
  const hookSelect = hookPurpose && data[`after${hookPurpose}Select`];
  ```
  For updates, `hookPurpose = "Update"`, so it looks for `afterUpdateSelect` — which is empty because we registered `afterSave`, not `afterUpdate`
- The `addHookPurpose` parameter that could check a secondary select is `void 0` for updates (line 10433)
- Since no hook columns are found, no `RETURNING` clause is added to the UPDATE SQL
- The hook fires but receives the raw row count (`1`) instead of the selected column data

On the **create** path, this bug is masked because creates always include `RETURNING *` regardless of hook column selection.

## Expected behavior

- `afterSave` hooks should receive an array of records (or the types should be updated to reflect the new single-object behavior)
- When `afterSave(["columns"], cb)` is registered, UPDATE queries should include those columns in the RETURNING clause so the hook receives actual column data, not the row count

## Versions

- orchid-orm: 1.64.1
- pqb: 0.61.5
